project: maps

targets:
  - SailfishOS-4.0.1.48-armv7hl
  - SailfishOS-4.0.1.48-aarch64
  - SailfishOS-4.0.1.48-i486

rpms: RPMS

buildoptions: -j6

options:
  - keep-release-from-spec

macros:
  - sailfish_build 1
  - jollastore 1
  - _buildhost tbuilder

shadow_builds:
  - harbour-osmscout-server.spec
  - harbour-pure-maps.spec
  - s2geometry.spec
  - valhalla-lite-devel.spec
